name: Deploy to personal site
on: [push]
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: Dionysopoulos.me
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy over SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "joomla_extensions_development.xml,advice.xml,components.xml,concepts.xml,fdl.xml,gpl.xml,modules.xml,plugins.xml,preface.xml,templates.xml,assets/JoomlaExtensionNamespace.png"
          target: ${{ secrets.SSH_PATH }}